-- Extract view information from SAP HANA
SELECT
    V.COMMENTS AS REMARKS,
    V.CREATE_TIME,
    CAST(V.DEFINITION AS NVARCHAR) AS VIEW_DEFINITION,
    'DEFAULT' AS TABLE_CAT,
    V.SCHEMA_NAME AS TABLE_SCHEM,
    V.VIEW_NAME AS TABLE_NAME,
    V.VIEW_OID AS TABLE_OID,
    'VIEW' AS TABLE_TYPE,
    NULL AS HAS_PARTITIONS,
    NULL AS ROW_COUNT,
    NULL AS BYTES,
    NULL AS AUTO_MERGE_ON,
    NULL AS AUTO_OPTIMIZE_COMPRESSION_ON,
    NULL AS COMMIT_ACTION,
    NULL AS COMPRESSED_EXTKEY,
    NULL AS FIXED_PART_SIZE,
    V.HAS_MASKED_COLUMNS,
    NULL AS HAS_PRIMARY_KEY,
    NULL AS HAS_RECORD_COMMIT_TIMESTAMP,
    V.HAS_STRUCTURED_PRIVILEGE_CHECK,
    NULL AS HAS_TEXT_FIELDS,
    NULL AS IS_COLUMN_TABLE,
    NULL AS IS_INSERT_ONLY,
    NULL AS IS_LOGGED,
    NULL AS IS_PARTIAL_PRELOAD,
    NULL AS IS_PRELOAD,
    NULL AS IS_PUBLIC,
    NULL AS IS_REPLICA,
    NULL AS IS_REPLICATION_LOG_ENABLED,
    NULL AS IS_SYSTEM_TABLE,
    NULL AS IS_TEMPORARY,
    NULL AS IS_USER_DEFINED_TYPE,
    NULL AS PERSISTENT_MEMORY,
    NULL AS ROW_ORDER_TYPE,
    NULL AS TEMPORAL_TYPE,
    NULL AS TEMPORARY_TABLE_TYPE,
    NULL AS UNLOAD_PRIORITY,
    NULL AS USES_DIMFN_CACHE,
    NULL AS USES_EXTKEY,
    NULL AS USES_QUEUE_TABLE
FROM
    SYS.VIEWS V
WHERE
    V.SCHEMA_NAME NOT IN (
        'SYSTEM', 
        'SYS',
        'SYSHDL',
        'BROKER_PO_USER',
        'BROKER_USER',
        'HANA_XS_BASE',
        'UIS',
        'PUBLIC'
    )
    AND V.SCHEMA_NAME NOT LIKE 'SYS\_%' ESCAPE '\\'
    AND V.SCHEMA_NAME NOT LIKE '\_SYS\_%' ESCAPE '\\'
    AND V.SCHEMA_NAME NOT LIKE 'SYSHDL\_%' ESCAPE '\\'
    AND V.SCHEMA_NAME NOT LIKE 'SAP\_%' ESCAPE '\\'
    AND V.SCHEMA_NAME NOT LIKE '\_SAP\_%' ESCAPE '\\'
    AND V.SCHEMA_NAME NOT LIKE 'PAL\_%' ESCAPE '\\' 