SELECT
    V.SCHEMA_NAME AS TABLE_SCHEM,
    V.VIEW_NAME,
    VC.COLUMN_NAME,
    VC.DATA_TYPE_NAME AS TYPE_NAME,
    VC.POSITION AS ORDINAL_POSITION,
    VC.DEFAULT_VALUE AS COLUMN_DEFAULT,
    VC.IS_NULLABLE,
    VC.SCALE AS NUMERIC_SCALE,
    VC.LENGTH AS CHARACTER_MAXIMUM_LENGTH,
    VC.PRECISION,
    VC.COMMENTS AS REMARKS,
    'DEFAULT' AS TABLE_CAT,
    AO.PACKAGE_ID
FROM
    SYS.VIEW_COLUMNS VC
JOIN
    SYS.VIEWS V ON VC.VIEW_OID = V.VIEW_OID
JOIN
    _SYS_REPO.ACTIVE_OBJECT AO
    ON AO.OBJECT_NAME = V.VIEW_NAME
    AND AO.SCHEMA_NAME = V.SCHEMA_NAME
WHERE
    AO.OBJECT_SUFFIX = 'calculationview'
    AND V.SCHEMA_NAME NOT IN (
        'SYSTEM',
        'SYS',
        'SYSHDL',
        'BROKER_PO_USER',
        'BROKER_USER',
        'HANA_XS_BASE',
        'UIS',
        'PUBLIC'
    )
    AND concat('DEFAULT', concat('.', V.SCHEMA_NAME)) !~ '{normalized_exclude_regex}'
    AND concat('DEFAULT', concat('.', V.SCHEMA_NAME)) ~ '{normalized_include_regex}'; 