SELECT 
    'DEFAULT' AS DATABASE_NAME,
    'SAP HANA Database' AS DATABASE_DESCRIPTION,
    VERSION AS DATABASE_VERSION,
    HOST AS DATABASE_HOST,
    PORT AS DATABASE_PORT,
    START_TIME AS DATABASE_CREATE_TIME,
    'SAP HANA' AS DATABASE_TYPE
FROM 
    M_DATABASE
LIMIT 1; 