SELECT
    V.COMMENTS AS REMARKS,
    V.CREATE_TIME,
    CAST(V.DEFINITION AS NVARCHAR) AS VIEW_DEFINITION,
    'DEFAULT' AS TABLE_CAT,
    V.SCHEMA_NAME AS TABLE_SCHEM,
    V.VIEW_NAME AS TABLE_NAME,
    V.VIEW_OID AS TABLE_OID,
    'VIEW' AS TABLE_TYPE,
    V.HAS_STRUCTURED_PRIVILEGE_CHECK,
    V.IS_VALID,
    V.IS_COLUMN_VIEW
FROM
    SYS.VIEWS V
WHERE
    V.SCHEMA_NAME NOT IN (
        'SYSTEM', 
        'SYS',
        'SYSHDL',
        'BROKER_PO_USER',
        'BROKER_USER',
        'HANA_XS_BASE',
        'UIS',
        'PUBLIC',
        'SAPHANADB',
        'DBACOCKPIT',
        'SAPDBCTRL'
    )
    AND V.SCHEMA_NAME NOT LIKE 'SYS\_%' ESCAPE '\'
    AND V.SCHEMA_NAME NOT LIKE '\_SYS\_%' ESCAPE '\'
    AND V.SCHEMA_NAME NOT LIKE 'SYSHDL\_%' ESCAPE '\'
    AND V.SCHEMA_NAME NOT LIKE 'SAP\_%' ESCAPE '\'
    AND V.SCHEMA_NAME NOT LIKE '\_SAP\_%' ESCAPE '\'
    AND V.SCHEMA_NAME NOT LIKE 'PAL\_%' ESCAPE '\'
    AND V.SCHEMA_NAME NOT LIKE 'FDT\_%' ESCAPE '\'
    AND V.SCHEMA_NAME NOT LIKE 'XSSQLCC\_AUTO\_USER\_%' ESCAPE '\'
    AND concat('DEFAULT', concat('.', V.SCHEMA_NAME)) !~ '{normalized_exclude_regex}'
    AND concat('DEFAULT', concat('.', V.SCHEMA_NAME)) ~ '{normalized_include_regex}'; 