-- Extract table information from SAP HANA
SELECT
    T.COMMENTS AS REMARKS,
    T.CREATE_TIME,
    NULL AS VIEW_DEFINITION,
    'DEFAULT' AS TABLE_CAT,
    T.SCHEMA_NAME AS TABLE_SCHEM,
    T.TABLE_NAME,
    T.TABLE_OID,
    T.TABLE_TYPE,
    MT.IS_PARTITIONED AS HAS_PARTITIONS,
    MT.RECORD_COUNT AS ROW_COUNT,
    MT.TABLE_SIZE as BYTES,
    T.AUTO_MERGE_ON,
    T.AUTO_OPTIMIZE_COMPRESSION_ON,
    T.COMMIT_ACTION,
    T.COMPRESSED_EXTKEY,
    T.FIXED_PART_SIZE,
    T.HAS_MASKED_COLUMNS,
    T.HAS_PRIMARY_KEY,
    T.HAS_RECORD_COMMIT_TIMESTAMP,
    T.HAS_STRUCTURED_PRIVILEGE_CHECK,
    T.HAS_TEXT_FIELDS,
    T.IS_COLUMN_TABLE,
    T.IS_INSERT_ONLY,
    T.IS_LOGGED,
    T.IS_PARTIAL_PRELOAD,
    T.IS_PRELOAD,
    T.IS_PUBLIC,
    T.IS_REPLICA,
    T.IS_REPLICATION_LOG_ENABLED,
    T.IS_SYSTEM_TABLE,
    T.IS_TEMPORARY,
    T.IS_USER_DEFINED_TYPE,
    T.PERSISTENT_MEMORY,
    T.ROW_ORDER_TYPE,
    T.TEMPORAL_TYPE,
    T.TEMPORARY_TABLE_TYPE,
    T.UNLOAD_PRIORITY,
    T.USES_DIMFN_CACHE,
    T.USES_EXTKEY,
    T.USES_QUEUE_TABLE
FROM
    SYS.TABLES T
    LEFT JOIN SYS.M_TABLES MT
        ON MT.SCHEMA_NAME = T.SCHEMA_NAME
        AND MT.TABLE_NAME = T.TABLE_NAME
WHERE
    T.SCHEMA_NAME NOT IN (
        'SYSTEM',
        'SYS',
        'SYSHDL',
        'BROKER_PO_USER',
        'BROKER_USER',
        'HANA_XS_BASE',
        'UIS',
        'PUBLIC'
    )
    AND T.SCHEMA_NAME NOT LIKE 'SYS\_%' ESCAPE '\\'
    AND T.SCHEMA_NAME NOT LIKE '\_SYS\_%' ESCAPE '\\'
    AND T.SCHEMA_NAME NOT LIKE 'SYSHDL\_%' ESCAPE '\\'
    AND T.SCHEMA_NAME NOT LIKE 'SAP\_%' ESCAPE '\\'
    AND T.SCHEMA_NAME NOT LIKE '\_SAP\_%' ESCAPE '\\'
    AND T.SCHEMA_NAME NOT LIKE 'PAL\_%' ESCAPE '\\'
    AND T.TABLE_TYPE = 'TABLE' 