SELECT
    'DEFAULT' AS TABLE_CAT,
    TC.SCHEMA_NAME AS TABLE_SCHEM,
    TC.TABLE_NAME,
    TC.COLUMN_NAME,
    TC.COMMENTS as REMARKS,
    TC.DATA_TYPE_NAME as TYPE_NAME,
    TC.POSITION as ORDINAL_POSITION,
    TC.DEFAULT_VALUE AS COLUMN_DEFAULT,
    TC.IS_NULLABLE AS IS_NULLABLE,
    TC.SCALE AS NUMERIC_SCALE,
    TC.LENGTH AS CHARACTER_MAXIMUM_LENGTH,
    IC.CONSTRAINT AS CONSTRAINT_TYPE,
    RC.REFERENCED_COLUMN_NAME AS REFERENCED_COLUMN_NAME,
    TC.LENGTH AS DATA_LENGTH,
    TC.PRECISION AS PRECISION,
    TC.IS_HIDDEN,
    'DEFAULT' AS DATABASE_NAME
FROM
    SYS.TABLE_COLUMNS TC
    LEFT JOIN SYS.TABLES T
      ON T.SCHEMA_NAME = TC.SCHEMA_NAME
      AND T.TABLE_NAME = TC.TABLE_NAME
    LEFT JOIN SYS.TABLE_COLUMNS_ODBC TCO
      ON TCO.SCHEMA_NAME = TC.SCHEMA_NAME
      AND TCO.TABLE_NAME = TC.TABLE_NAME
      AND TCO.COLUMN_NAME = TC.COLUMN_NAME
    LEFT JOIN SYS.INDEX_COLUMNS IC
      ON IC.SCHEMA_NAME = TC.SCHEMA_NAME
      AND IC.TABLE_NAME = TC.TABLE_NAME
      AND IC.COLUMN_NAME = TC.COLUMN_NAME
    LEFT JOIN SYS.REFERENTIAL_CONSTRAINTS RC
      ON RC.SCHEMA_NAME = TC.SCHEMA_NAME
      AND RC.TABLE_NAME = TC.TABLE_NAME
      AND RC.COLUMN_NAME = TC.COLUMN_NAME
WHERE
    TC.SCHEMA_NAME NOT IN (
        'SYSTEM',
        'SYS',
        'SYSHDL',
        'BROKER_PO_USER',
        'BROKER_USER',
        'HANA_XS_BASE',
        'UIS',
        'PUBLIC',
        'SAPHANADB',
        'DBACOCKPIT',
        'SAPDBCTRL'
    )
    AND TC.SCHEMA_NAME NOT LIKE 'SYS\_%' ESCAPE '\'
    AND TC.SCHEMA_NAME NOT LIKE '\_SYS\_%' ESCAPE '\'
    AND TC.SCHEMA_NAME NOT LIKE 'SYSHDL\_%' ESCAPE '\'
    AND TC.SCHEMA_NAME NOT LIKE 'SAP\_%' ESCAPE '\'
    AND TC.SCHEMA_NAME NOT LIKE '\_SAP\_%' ESCAPE '\'
    AND TC.SCHEMA_NAME NOT LIKE 'PAL\_%' ESCAPE '\'
    AND TC.SCHEMA_NAME NOT LIKE 'FDT\_%' ESCAPE '\'
    AND TC.SCHEMA_NAME NOT LIKE 'XSSQLCC\_AUTO\_USER\_%' ESCAPE '\'
    AND concat('DEFAULT', concat('.', TC.SCHEMA_NAME)) !~ '{normalized_exclude_regex}'
    AND concat('DEFAULT', concat('.', TC.SCHEMA_NAME)) ~ '{normalized_include_regex}'; 