-- Extract calculation view information from SAP HANA
SELECT 
    'DEFAULT' AS TABLE_CAT,
    SCHEMA_NAME AS TABLE_SCHEM,
    OBJECT_NAME AS VIEW_NAME,
    PACKAGE_ID AS PACKAGE_ID,
    VERSION_ID,
    ACTIVATED_AT,
    ACTIVATED_BY,
    CAST(CDATA AS NVARCHAR) AS ROUTINE_DEFINITION
FROM
    _SYS_REPO.ACTIVE_OBJECT
    JOIN
    SYS.VIEWS ON concat(concat(PACKAGE_ID,'/'),OBJECT_NAME) = VIEW_NAME
WHERE
    OBJECT_SUFFIX = 'calculationview' 