-- Extract procedure information from SAP HANA
SELECT
    'DEFAULT' as PROCEDURE_CAT,
    SCHEMA_NAME as PROCEDURE_SCHEM,
    SCHEMA_NAME as TABLE_SCHEM,
    PROCEDURE_NAME,
    PROCEDURE_TYPE,
    CAST(DEFINITION AS NVARCHAR) ROUTINE_DEFINITION
FROM
    SYS.PROCEDURES
WHERE
    SCHEMA_NAME NOT IN (
        'SYSTEM',
        'SYS',
        'SYSHDL',
        'BROKER_USER',
        'BROKER_PO_USER',
        'HANA_XS_BASE',
        'UIS',
        'PUBLIC'
    )
    AND SCHEMA_NAME NOT LIKE 'SYS\_%' ESCAPE '\\'
    AND SCHEMA_NAME NOT LIKE '\_SYS\_%' ESCAPE '\\'
    AND SCHEMA_NAME NOT LIKE 'SYSHDL\_%' ESCAPE '\\'
    AND SCHEMA_NAME NOT LIKE 'SAP\_%' ESCAPE '\\'
    AND SCHEMA_NAME NOT LIKE '\_SAP\_%' ESCAPE '\\'
    AND SCHEMA_NAME NOT LIKE 'PAL\_%' ESCAPE '\\' 