columns:
  - name: typeName
    source_query: "'Database'"
    
  - name: attributes.name
    source_query: DATABASE_NAME
    
  - name: attributes.qualifiedName
    source_query: concat(connection_qualified_name, '/', DATABASE_NAME)
    source_columns: [connection_qualified_name, DATABASE_NAME]
    
  - name: attributes.description
    source_query: DATABASE_DESCRIPTION
    
  - name: attributes.prodOrOther
    source_query: "'PROD'"
    
  - name: attributes.createTime
    source_query: DATABASE_CREATE_TIME
    
  - name: attributes.databaseVersion
    source_query: DATABASE_VERSION
    
  - name: attributes.databaseType
    source_query: DATABASE_TYPE
    
  - name: attributes.connectionQualifiedName
    source_query: connection_qualified_name 