columns:
  - name: typeName
    source_query: "'Schema'"
    
  - name: attributes.name
    source_query: SCHEMA_NAME
    
  - name: attributes.qualifiedName
    source_query: concat(connection_qualified_name, '/', TABLE_CAT, '/', SCHEMA_NAME)
    source_columns: [connection_qualified_name, TABLE_CAT, SCHEMA_NAME]
    
  - name: attributes.databaseName
    source_query: TABLE_CAT
    
  - name: attributes.databaseQualifiedName
    source_query: concat(connection_qualified_name, '/', TABLE_CAT)
    source_columns: [connection_qualified_name, TABLE_CAT]
    
  - name: attributes.description
    source_query: REMARKS
    
  - name: attributes.createTime
    source_query: SCHEMA_CREATE_TIME
    
  - name: attributes.owner
    source_query: SCHEMA_OWNER
    
  - name: attributes.connectionQualifiedName
    source_query: connection_qualified_name 